---
name: ros-infrastructure pytest
description: Continuous integration for ros-infrastructure repositories
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        echo ::group::Initialize environment
        VENV=$(mktemp -d)
        python -m venv $VENV
        if [ -f $VENV/Scripts/activate ]; then
          . $VENV/Scripts/activate
        else
          . $VENV/bin/activate
        fi
        python -m pip install -U pip setuptools
        echo ::endgroup::

        echo ::group::Install package
        python -m pip install -U -e .[test] --no-deps
        echo ::endgroup::

        echo ::group::Install dependencies
        # Remove this package from constraints
        PKG_NAME=$(pip list -l -e --format json | jq '.[0].name' -r | tr _ -)
        cp -a ${GITHUB_ACTION_PATH}/constraints{,-heads,-pins}.txt ./
        sed -i.orig "s/^${PKG_NAME}@.*//g" constraints-heads.txt
        # Install dependencies, including 'test' extras, as well as pytest-cov
        python -m pip install -U -e .[test] pytest-cov -c constraints.txt
        echo ::endgroup::

        echo ::group::Run tests
        python -m pytest \
          --cov --cov-branch \
          --cov-report xml:coverage.xml \
          --cov-config setup.cfg
        echo ::endgroup::
