---
name: Run tests

on:  # yamllint disable-line rule:truthy
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  canary:
    uses: ./.github/workflows/pytest.yaml
    with:
      # Choose rosdistro for a canary build. It has ros-infrastructure
      # dependencies and installs scripts, so exercieses a fair amount of the
      # CI action features.
      repository: ros-infrastructure/rosdistro
      # Use HEAD to find strategy.json file instead of the tip of
      # ros-infrastructure/ci
      setup-repository: ''
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: yamllint -f github .
